In [1]:
import pandas as pd 

df = pd.read_csv("/home/bekah/m3_papers/20260310/l1b_rdn_hdr_info.csv")

In [2]:
df

,Unnamed: 0,obs_filename,id,obs_type,version,obs_temperature,obs_beta_angle,cal_dark_signal_image,cal_bad_detector_map,cal_flat_field_image,calibrated_data_version
0,0,M3G20090208T021836_V03_RDN.HDR,M3G20090208T021836,G,V03,150.02,51.03,M3G20090208T014050_V01_L0.IMG,M3G20090208T014050_V01_BDE.IMG,M3G20090208T021836_V01_FF.IMG,u2
1,1,M3G20090205T150614_V03_RDN.HDR,M3G20090205T150614,G,V03,151.48,48.69,M3G20090205T144053_V01_L0.IMG,M3G20090205T144053_V01_BDE.IMG,M3G20090205T150614_V01_FF.IMG,u2
2,2,M3G20090712T133812_V01_RDN.HDR,M3G20090712T133812,G,V01,157.94,23.80,M3G20090712T132302_V01_L0.IMG,M3G20090712T132302_V01_BDE.IMG,M3G20090712T133812_V01_FF.IMG,r
3,3,M3T20090416T030323_V01_RDN.HDR,M3T20090416T030323,T,V01,146.00,59.82,M3T20090416T021319_V01_L0.IMG,M3T20090416T021319_V01_BDE.IMG,M3T20090416T030323_V01_FF.IMG,r
4,4,M3G20090209T042503_V02_RDN.HDR,M3G20090209T042503,G,V02,149.44,52.07,M3G20090209T051311_V01_L0.IMG,M3G20090209T051311_V01_BDE.IMG,M3G20090209T033051_V01_FF.IMG,r
...,...,...,...,...,...,...,...,...,...,...,...
1334,1334,M3G20090617T045633_V03_RDN.HDR,M3G20090617T045633,G,V03,167.90,0.91,M3G20090617T045332_V01_L0.IMG,M3G20090617T045332_V01_BDE.IMG,M3G20090617T045633_V01_FF.IMG,u2
1335,1335,M3G20090717T211502_V01_RDN.HDR,M3G20090717T211502,G,V01,156.53,28.90,M3G20090717T211202_V01_L0.IMG,M3G20090717T211202_V01_BDE.IMG,M3G20090717T211502_V01_FF.IMG,r
1336,1336,M3G20090214T055332_V03_RDN.HDR,M3G20090214T055332,G,V03,146.79,56.89,M3G20090214T051333_V01_L0.IMG,M3G20090214T051333_V01_BDE.IMG,M3G20090214T055332_V01_FF.IMG,u2
1337,1337,M3G20090211T032906_V03_RDN.HDR,M3G20090211T032906,G,V03,148.48,53.93,M3G20090211T042632_V01_L0.IMG,M3G20090211T042632_V01_BDE.IMG,M3G20090211T032906_V01_FF.IMG,u2
1338,1338,M3G20090613T161036_V03_RDN.HDR,M3G20090613T161036,G,V03,165.55,3.49,M3G20090613T155122_V01_L0.IMG,M3G20090613T155122_V01_BDE.IMG,M3G20090613T161036_V01_FF.IMG,u2

In [3]:
df['bde'] = df['cal_bad_detector_map'].str.split("_", expand=True)[0]
df['dark'] = df['cal_dark_signal_image'].str.split("_", expand=True)[0]
df['flat'] = df['cal_flat_field_image'].str.split("_", expand=True)[0]

In [7]:
df[df['bde']=='M3G20090601T102652']

,Unnamed: 0,obs_filename,id,obs_type,version,obs_temperature,obs_beta_angle,cal_dark_signal_image,cal_bad_detector_map,cal_flat_field_image,calibrated_data_version,bde,dark,flat
83,83,M3G20090602T082937_V01_RDN.HDR,M3G20090602T082937,G,V01,160.87,14.43,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090602T074711_V01_FF.IMG,r,M3G20090601T102652,M3G20090603T174201,M3G20090602T074711
223,223,M3G20090601T193005_V03_RDN.HDR,M3G20090601T193005,G,V03,159.85,14.95,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090601T235923_V01_FF.IMG,u2,M3G20090601T102652,M3G20090603T174201,M3G20090601T235923
502,502,M3G20090601T235923_V03_RDN.HDR,M3G20090601T235923,G,V03,160.47,14.81,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090601T235923_V01_FF.IMG,u2,M3G20090601T102652,M3G20090603T174201,M3G20090601T235923
548,548,M3G20090601T193005_V01_RDN.HDR,M3G20090601T193005,G,V01,159.85,14.95,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090601T193005_V01_FF.IMG,r,M3G20090601T102652,M3G20090603T174201,M3G20090601T193005
610,610,M3G20090601T145212_V01_RDN.HDR,M3G20090601T145212,G,V01,159.93,15.15,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090601T145212_V01_FF.IMG,r,M3G20090601T102652,M3G20090603T174201,M3G20090601T145212
650,650,M3G20090602T121452_V01_RDN.HDR,M3G20090602T121452,G,V01,160.47,14.28,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090602T121452_V01_FF.IMG,r,M3G20090601T102652,M3G20090603T174201,M3G20090602T121452
680,680,M3G20090602T074711_V03_RDN.HDR,M3G20090602T074711,G,V03,160.87,14.48,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090602T074711_V01_FF.IMG,u2,M3G20090601T102652,M3G20090603T174201,M3G20090602T074711
738,738,M3G20090602T124100_V03_RDN.HDR,M3G20090602T124100,G,V03,160.39,14.28,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090602T124100_V01_FF.IMG,u2,M3G20090601T102652,M3G20090603T174201,M3G20090602T124100
861,861,M3G20090602T121452_V03_RDN.HDR,M3G20090602T121452,G,V03,160.47,14.28,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090602T124100_V01_FF.IMG,u2,M3G20090601T102652,M3G20090603T174201,M3G20090602T124100
890,890,M3G20090601T145212_V03_RDN.HDR,M3G20090601T145212,G,V03,159.93,15.15,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090601T145212_V01_FF.IMG,u2,M3G20090601T102652,M3G20090603T174201,M3G20090601T145212
977,977,M3G20090601T104211_V01_RDN.HDR,M3G20090601T104211,G,V01,159.70,15.29,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090601T104211_V01_FF.IMG,r,M3G20090601T102652,M3G20090603T174201,M3G20090601T104211
1022,1022,M3G20090601T104211_V03_RDN.HDR,M3G20090601T104211,G,V03,159.70,15.29,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090601T145212_V01_FF.IMG,u2,M3G20090601T102652,M3G20090603T174201,M3G20090601T145212
1139,1139,M3G20090602T074711_V01_RDN.HDR,M3G20090602T074711,G,V01,160.87,14.48,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090602T074711_V01_FF.IMG,r,M3G20090601T102652,M3G20090603T174201,M3G20090602T074711
1184,1184,M3G20090602T124100_V01_RDN.HDR,M3G20090602T124100,G,V01,160.39,14.28,M3G20090603T174201_V01_L0.IMG,M3G20090601T102652_V01_BDE.IMG,M3G20090602T124100_V01_FF.IMG,r,M3G20090601T102652,M3G20090603T174201,M3G20090602T124100

In [10]:
df[df['dark'] != df['bde']]['dark'].unique()

array(['M3G20090603T174201', 'M3G20090207T174850', 'M3G20090626T182643',
       'M3G20090207T155050'], dtype=object)

In [ ]:
temps = pd.read_fwf("/home/bekah/m3_papers/20260310/m3_detector_temperature.tab")

In [ ]:
temps

In [ ]:
# want to get temperature for every flat, bde, and dark signal image vs the observation 
# temp to see how similar all the temperatures are. if there's an observation where 
# they are significantly different, that seems like a problem. 

temp_mapping = temps.set_index('id')['temp']
df['obs_temp'] = df['id'].map(temp_mapping)
df['flat_temp'] = df['flat'].map(temp_mapping)
df['dark_temp'] = df['dark'].map(temp_mapping)
df['bde_temp'] = df['bde'].map(temp_mapping)

In [ ]:
df['max_diff'] = df['obs_temp'] - df['flat_temp']
df['max_diff'].describe()

In [ ]:
df['max_diff_dark'] = df['obs_temp'] - df['dark_temp']
df['max_diff_dark'].describe()

In [ ]:
df['max_diff_bde'] = df['obs_temp'] - df['bde_temp']
df['max_diff_bde'].describe()

In [ ]:
df['max_diff_flat_dark'] = df['flat_temp'] - df['dark_temp']
df['max_diff_flat_dark'].describe()

In [ ]:
df[df['max_diff_flat_dark'] <= -4]

In [ ]:
df[df['max_diff_flat_dark'] <= -4]['bde']

In [ ]:
df[df['max_diff_flat_dark'] <= -4]['dark']

In [ ]:
df[df['bde'] == 'M3G20090601T102652']

In [ ]:
import matplotlib.pyplot as plt